[cargo-new]
name = 'Tamas Demeter-Haludka'
email = 'tamas@demeter-haludka.hu'
vcs = 'git'

[build]
jobs = 16
rustflags = [
	"-Ctarget-cpu=native",
	"-Ccodegen-units=1"
]

[profile.dev]
debug-assertions = true
debug = true

[term]
verbose = true

[alias]
b = "build"
t = "test"
r = "run"
rr = "run --release"
