#pragma once

#define STARTUP_SONG SONG(PLANCK_SOUND)
#define AUDIO_INIT_DELAY 1000
#define TEMPO_DEFAULT 60
#define AUDIO_ENABLE_TONE_MULTIPLEXING
#define AUDIO_TONE_MULTIPLEXING_RATE_DEFAULT 10
#define PREVENT_STUCK_MODIFIERS
#define AUDIO_VOICES
#define PERMISSIVE_HOLD
#define PITCH_STANDARD_A 880.0f
#define TAP_CODE_DELAY 5
#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY

#undef DEBOUNCING_DELAY
#define DEBOUNCING_DELAY 15

#define NO_ACTION_ONESHOT

#define DISABLE_LEADER

#ifndef NO_DEBUG
#define NO_DEBUG
#endif // !NO_DEBUG
#if !defined(NO_PRINT) && !defined(CONSOLE_ENABLE)
#define NO_PRINT
#endif // !NO_PRINT
