local hop = require("hop")
hop.setup({})

vim.keymap.set("", "<leader>hw", function()
	hop.hint_words()
end, { desc = "hop words" })
vim.keymap.set("", "<leader>hc", function()
	hop.hint_char1()
end, { desc = "hop char" })
vim.keymap.set("", "<leader>hp", function()
	hop.hint_patterns()
end, { desc = "hop patterns" })
